In [151]:
%matplotlib inline
from copy import deepcopy
import numpy as np
import pandas as pd
import seaborn as sns
sns.set()
from matplotlib import pyplot as plt
plt.rcParams['figure.figsize'] = (16,9)
plt.style.use('ggplot')

# Upload and Preprocess Data

In [152]:
df1 = pd.read_csv('crunchbase_aerospace.csv')
df2 = pd.read_csv('crunchbase_ai.csv')
df3 = pd.read_csv('crunchbase_biotech.csv')
df4 = pd.read_csv('crunchbase_energy.csv')
df5 = pd.read_csv('crunchbase_neurotech.csv')

df1

Organization Name                              Organization Name URL  \
0              SpaceX  https://www.crunchbase.com/organization/space-...   
1             Overair    https://www.crunchbase.com/organization/overair   
2         Blue Origin  https://www.crunchbase.com/organization/blue-o...   
3                 DJI        https://www.crunchbase.com/organization/dji   
4        Sierra Space  https://www.crunchbase.com/organization/sierra...   
..                ...                                                ...   
995         Jetoptera  https://www.crunchbase.com/organization/jetoptera   
996               DRG   https://www.crunchbase.com/organization/drg-adb1   
997         iniVation  https://www.crunchbase.com/organization/inivation   
998       UAV Factory  https://www.crunchbase.com/organization/uav-fa...   
999          SAT Corp   https://www.crunchbase.com/organization/sat-corp   

    Operating Status Company Type IPO Status Estimated Revenue Range  \
0             Active   For Profit    Private             $1B to $10B   
1             Active   For Profit    Private                     NaN   
2             Active   For Profit    Private          $100M to $500M   
3             Active   For Profit    Private            $10M to $50M   
4             Active   For Profit    Private                     NaN   
..               ...          ...        ...                     ...   
995           Active   For Profit    Private             $1M to $10M   
996           Active   For Profit    Private           $50M to $100M   
997           Active   For Profit    Private           Less than $1M   
998           Active   For Profit    Private           Less than $1M   
999           Active   For Profit    Private             $1M to $10M   

    Number of Employees                   Headquarters Location  \
0                10001+    Hawthorne, California, United States   
1               101-250    Santa Ana, California, United States   
2             1001-5000         Kent, Washington, United States   
3                10001+              Shenzhen, Guangdong, China   
4             1001-5000     Louisville, Colorado, United States   
..                  ...                                     ...   
995                1-10      Edmonds, Washington, United States   
996            501-1000  Oklahoma City, Oklahoma, United States   
997               11-50             Zürich, Zurich, Switzerland   
998               11-50      Irvington, New York, United States   
999             251-500    Sunnyvale, California, United States   

            Last Funding Type  Total Funding Amount  \
0    Venture - Series Unknown          9.510344e+09   
1                    Series B          1.700000e+08   
2                       Grant          1.673500e+08   
3              Private Equity          1.050000e+08   
4                    Series A          1.400000e+09   
..                        ...                   ...   
995                       NaN                   NaN   
996                       NaN                   NaN   
997                      Seed                   NaN   
998                       NaN                   NaN   
999                       NaN                   NaN   

    Total Funding Amount Currency  Total Funding Amount Currency (in USD)  \
0                             USD                            9.510344e+09   
1                             USD                            1.700000e+08   
2                             USD                            1.673500e+08   
3                             USD                            1.050000e+08   
4                             USD                            1.400000e+09   
..                            ...                                     ...   
995                           NaN                                     NaN   
996                           NaN                                     NaN   
997                           NaN                                  

In [201]:
df1['Industries'] = 'Aerospace'
df2['Industries'] = 'Artificial Intelligence'
df3['Industries'] = 'Biotechnology'
df4['Industries'] = 'Energy'
df5['Industries'] = 'Neurotech'

In [202]:
# stick together dataframes
data = pd.concat([df1,df2,df3,df4,df5])
data = data.reset_index()
data

index                  Organization Name  \
0         0                             SpaceX   
1         1                            Overair   
2         2                        Blue Origin   
3         3                                DJI   
4         4                       Sierra Space   
...     ...                                ...   
4663    663          California NeuroInstitute   
4664    664  Advanced Interventional Catheters   
4665    665                        NeuronBasic   
4666    666                                TWI   
4667    667         Advanced Medical Resources   

                                  Organization Name URL Operating Status  \
0     https://www.crunchbase.com/organization/space-...           Active   
1       https://www.crunchbase.com/organization/overair           Active   
2     https://www.crunchbase.com/organization/blue-o...           Active   
3           https://www.crunchbase.com/organization/dji           Active   
4     https://www.crunchbase.com/organization/sierra...           Active   
...                                                 ...              ...   
4663  https://www.crunchbase.com/organization/califo...           Active   
4664  https://www.crunchbase.com/organization/advanc...           Active   
4665  https://www.crunchbase.com/organization/neuron...           Active   
4666   https://www.crunchbase.com/organization/twi-025e           Active   
4667  https://www.crunchbase.com/organization/advanc...           Active   

     Company Type IPO Status Estimated Revenue Range Number of Employees  \
0      For Profit    Private             $1B to $10B              10001+   
1      For Profit    Private                     NaN             101-250   
2      For Profit    Private          $100M to $500M           1001-5000   
3      For Profit    Private            $10M to $50M              10001+   
4      For Profit    Private                     NaN           1001-5000   
...           ...        ...                     ...                 ...   
4663   For Profit    Private           Less than $1M                1-10   
4664   For Profit    Private                     NaN                 NaN   
4665   For Profit    Private                     NaN                 NaN   
4666   For Profit    Private                     NaN               11-50   
4667   For Profit    Private                     NaN               11-50   

                     Headquarters Location         Last Funding Type  \
0     Hawthorne, California, United States  Venture - Series Unknown   
1     Santa Ana, California, United States                  Series B   
2          Kent, Washington, United States                     Grant   
3               Shenzhen, Guangdong, China            Private Equity   
4      Louisville, Colorado, United States                  Series A   
...                                    ...                       ...   
4663   San Jose, California, United States                       NaN   
4664                                   NaN                       NaN   
4665                                   NaN                  Series C   
4666                                   NaN                       NaN   
4667      Sugar Land, Texas, United States                       NaN   

      Total Funding Amount Total Funding Amount Currency  \
0             9.510344e+09                           USD   
1             1.700000e+08                           USD   
2             1.673500e+08                           USD   
3             1.050000e+08                           USD   
4             1.400000e+09                           USD   
...                    ...                           ...   
4663                   NaN                           NaN   
4664                   NaN                           NaN   
4665                   NaN                           NaN   
4666                   NaN                           NaN   
4667                   NaN                           N

In [203]:
data = data.drop(columns=['index','Organization Name URL', 'Operating Status', 'Company Type', 'Headquarters Location', 'Description', 'IPO Status', 'Estimated Revenue Range', 'Last Funding Type', 'Total Funding Amount Currency', 'Total Funding Amount', 'Full Description', 'Founded Date Precision', 'Website'])

In [204]:
data = data.dropna(subset=['Number of Employees', 'Total Funding Amount Currency (in USD)', 'Founded Date'])

In [205]:
data = data.drop_duplicates(subset=['Organization Name'])

In [206]:
def to_year(date):
    date = date[:4]
    age = 2022-int(date)
    return age

for i in data.index:
    if type(data['Founded Date'][i]) == str:
        data['Founded Date'][i] = to_year(data['Founded Date'][i])
    elif type(data['Founded Date'][i]) == float:
        print(data['Founded Date'][i])

<ipython-input-206-adfd51aefb62>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Founded Date'][i] = to_year(data['Founded Date'][i])


In [207]:
data = data.rename({'Founded Date': 'Age'}, axis=1)
data

Organization Name Number of Employees  \
0                   SpaceX              10001+   
1                  Overair             101-250   
2              Blue Origin           1001-5000   
3                      DJI              10001+   
4             Sierra Space           1001-5000   
...                    ...                 ...   
4444           Theraptosis                1-10   
4448           Limbic Life               11-50   
4468  Evotec Neurosciences               11-50   
4538               Neurome                1-10   
4585   Tikvah Therapeutics             101-250   

      Total Funding Amount Currency (in USD) Industries Age  
0                               9.510344e+09  Aerospace  20  
1                               1.700000e+08  Aerospace   3  
2                               1.673500e+08  Aerospace  22  
3                               1.050000e+08  Aerospace  16  
4                               1.400000e+09  Aerospace   1  
...                                      ...        ...  ..  
4444                            1.120251e+07  Neurotech  21  
4448                            8.874000e+03  Neurotech  15  
4468                            3.046585e+07  Neurotech  23  
4538                            9.000000e+06  Neurotech  22  
4585                            1.000000e+07  Neurotech  17  

[3848 rows x 5 columns]

In [208]:
list(data['Number of Employees'].unique())

['10001+',
 '101-250',
 '1001-5000',
 '251-500',
 '11-50',
 '51-100',
 '1-10',
 '501-1000',
 '5001-10000']

In [209]:
employee_counts = list(data['Number of Employees'].unique())
rounded_counts = [10001,101,1001,251,11,51,1,501,5001]
print(len(employee_counts))
print(len(rounded_counts))
print(employee_counts)

9
9
['10001+', '101-250', '1001-5000', '251-500', '11-50', '51-100', '1-10', '501-1000', '5001-10000']


In [210]:
employee_counts = ['11-50', '101-250', '51-100', '251-500', '1001-5000', '1-10', '10001+', '501-1000', '5001-10000']
rounded_counts = [10001,101,1001,251,11,51,1,501,5001]

def estimate_employees(employees):
    for i in range(len(employee_counts)):
        if employees == employee_counts[i]:
            employees = rounded_counts[i]
    return employees

for i in data.index:
    data['Number of Employees'][i] = estimate_employees(data['Number of Employees'][i])

<ipython-input-210-161e6dba435d>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Number of Employees'][i] = estimate_employees(data['Number of Employees'][i])


In [211]:
data

Organization Name Number of Employees  \
0                   SpaceX                   1   
1                  Overair                 101   
2              Blue Origin                  11   
3                      DJI                   1   
4             Sierra Space                  11   
...                    ...                 ...   
4444           Theraptosis                  51   
4448           Limbic Life               10001   
4468  Evotec Neurosciences               10001   
4538               Neurome                  51   
4585   Tikvah Therapeutics                 101   

      Total Funding Amount Currency (in USD) Industries Age  
0                               9.510344e+09  Aerospace  20  
1                               1.700000e+08  Aerospace   3  
2                               1.673500e+08  Aerospace  22  
3                               1.050000e+08  Aerospace  16  
4                               1.400000e+09  Aerospace   1  
...                                      ...        ...  ..  
4444                            1.120251e+07  Neurotech  21  
4448                            8.874000e+03  Neurotech  15  
4468                            3.046585e+07  Neurotech  23  
4538                            9.000000e+06  Neurotech  22  
4585                            1.000000e+07  Neurotech  17  

[3848 rows x 5 columns]

In [212]:
data['Industries'].unique()

array(['Aerospace', 'Artificial Intelligence', 'Biotechnology', 'Energy',
       'Neurotech'], dtype=object)

In [213]:
data = data.drop(['Organization Name'], axis=1)
data

Number of Employees  Total Funding Amount Currency (in USD) Industries  \
0                      1                            9.510344e+09  Aerospace   
1                    101                            1.700000e+08  Aerospace   
2                     11                            1.673500e+08  Aerospace   
3                      1                            1.050000e+08  Aerospace   
4                     11                            1.400000e+09  Aerospace   
...                  ...                                     ...        ...   
4444                  51                            1.120251e+07  Neurotech   
4448               10001                            8.874000e+03  Neurotech   
4468               10001                            3.046585e+07  Neurotech   
4538                  51                            9.000000e+06  Neurotech   
4585                 101                            1.000000e+07  Neurotech   

     Age  
0     20  
1      3  
2     22  
3     16  
4      1  
...   ..  
4444  21  
4448  15  
4468  23  
4538  22  
4585  17  

[3848 rows x 4 columns]

In [214]:
def get_unique_values_with_dictionary(values):
    new_values = {}

    for value in values:
        if value in new_values.keys():
            new_values[value] += 1
        else:
            new_values[value] = 1
    
    print(new_values)
    return new_values.keys()

get_unique_values_with_dictionary(list(data['Industries']))

{'Aerospace': 792, 'Artificial Intelligence': 989, 'Biotechnology': 929, 'Energy': 932, 'Neurotech': 206}


dict_keys(['Aerospace', 'Artificial Intelligence', 'Biotechnology', 'Energy', 'Neurotech'])

# Build Model

In [215]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [216]:
X = data[["Number of Employees","Total Funding Amount Currency (in USD)","Age"]]
Y = data[["Industries"]]
Xtrain, Xtest, ytrain, ytest = train_test_split(X, Y, random_state=1000)

In [217]:
model = GaussianNB()
model.fit(Xtrain, ytrain)

/Users/kokoxu/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GaussianNB()

In [218]:
# classes in sample
model.classes_

array(['Aerospace', 'Artificial Intelligence', 'Biotechnology', 'Energy',
       'Neurotech'], dtype='<U23')

In [219]:
# count of each class in sample
model.class_count_

array([594., 730., 693., 711., 158.])

In [220]:
# probability of each class in sample
model.class_prior_

array([0.20582121, 0.25294525, 0.24012474, 0.24636175, 0.05474705])

# Predicting Test Data

In [221]:
ypred = model.predict(Xtest)
accuracy = accuracy_score(ytest,ypred)
report = classification_report(ypred, ytest)
cm = confusion_matrix(ytest, ypred)

/Users/kokoxu/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kokoxu/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kokoxu/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [222]:
print("Classification report:")
print("Accuracy: ",accuracy)
print(report)
print("Confusion matrix:")
print(cm)

Classification report:
Accuracy:  0.2130977130977131
                         precision    recall  f1-score   support

              Aerospace       0.00      0.00      0.00         0
Artificial Intelligence       0.00      0.00      0.00        12
          Biotechnology       0.64      0.36      0.46       419
                 Energy       0.05      0.43      0.08        23
              Neurotech       0.92      0.09      0.16       508

               accuracy                           0.21       962
              macro avg       0.32      0.18      0.14       962
           weighted avg       0.76      0.21      0.29       962

Confusion matrix:
[[  0   2  31   3 162]
 [  0   0 154   5 100]
 [  0   0 151   5  80]
 [  0  10  79  10 122]
 [  0   0   4   0  44]]
